<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ClassInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassInfoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClassesByTeacher(User $teacher) {
        $qb = $this->createQueryBuilder('ci');
        $this->addTeacherJoin($qb, $teacher);
        return $qb->getQuery()->getResult();
    }

    public function findClassesByTeacherAndClassId(User $teacher, $id) {
        $qb = $this->createQueryBuilder('ci')
            ->where('ci.id = :id');
        $this->addTeacherJoin($qb, $teacher);
        return $qb
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Counts user classes
     *
     * @param  User $user
     * @return int
     */
    public function countUserClasses(User $user) {
        $query = $this->createQueryBuilder('ci')->select('COUNT(ci.id)');

        $this->addTeacherJoin($query, $user);

        return $query->getQuery()->getSingleScalarResult();
    }

    private function addTeacherJoin($qb, User $teacher) {
        return $qb->innerJoin('ci.user', 't')
            ->andWhere('t = :teacher')
            ->setParameter('teacher', $teacher);
    }
}
