<?php

namespace AppBundle\Repository;

/**
 * ClassInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
