<?php

namespace AppBundle\Repository;
use AppBundle\Entity\TeacherInfo;

/**
 * ClassInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClassInfoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClassesByTeacher(TeacherInfo $teacher)
    {
        $qb = $this->createQueryBuilder('ci');
        $this->addTeacherJoin($qb,$teacher);
        return $qb->getQuery()->getResult();
    }

    public function findClassesByTeacherAndClassName(TeacherInfo $teacher, $name)
    {
        $qb = $this->createQueryBuilder('ci')
            ->where('ci.name = :name');
        $this->addTeacherJoin($qb,$teacher);
        return $qb
            ->setParameter('name', $name)
            ->getQuery()
            ->getOneOrNullResult();
    }

    private function addTeacherJoin($qb, TeacherInfo $teacher)
    {
        return $qb->innerJoin('ci.teacher_info', 'ti')
            ->andWhere('ti = :teacher')
            ->setParameter('teacher', $teacher);
    }

}
