<?php

namespace AppBundle\Repository;

/**
 * StudentInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
