# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    always_authenticate_before_granting:  true

    encoders:
      FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                provider: fos_userbundle

            logout:
                path: /logout
                target: /login
            anonymous: ~
            oauth:
                resource_owners:
                #facebook:           "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /login
                failure_path: /login
                default_target_path: /
                check_path: /connect_check
                provider: fos_userbundle
                oauth_user_provider:
                    service: my_user_provider

    access_control:

        - { path: ^/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/class.*, role: ROLE_TEACHER }
        - { path: ^/activities.*, role: ROLE_TEACHER }
        - { path: ^/current.*, role: ROLE_TEACHER }
        - { path: ^/class.*, role: ROLE_TEACHER }
        - { path: ^/schedule.*, role: ROLE_TEACHER }
        - { path: ^/lesson.*, role: ROLE_TEACHER }

        - { path: ^/, role: [ROLE_TEACHER, ROLE_STUDENT, ROLE_NOT_ASSIGNED] }



